name: CI

on:
  push:
  pull_request:

jobs:

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    container: 'ubuntu:focal'
    strategy:
      matrix:
        type:
          - User
          - Developer
        ignition:
          - dome
          - citadel
        # Waiting the new minor release
        exclude:
          - type: User
            ignition: citadel

    steps:

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            wget \
            git \
            gpg-agent \
            ninja-build \
            build-essential \
            software-properties-common \
            python3 \
            python3-pip \
            python3-wheel
          pip3 install pytest pytest-xvfb
        env:
          DEBIAN_FRONTEND: noninteractive

      - uses: actions/checkout@master
      - run: git fetch --prune --unshallow

      - name: Compilation cache
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          # We include the commit sha in the cache key, as new cache entries are
          # only created if there is no existing entry for the key yet.
          key: ${{ runner.os }}-ccache-${{ matrix.ignition }}-${{ github.sha }}
          # Restore any ccache cache entry, if none for the key above exists
          restore-keys: |
            ${{ runner.os }}-ccache-${{ matrix.ignition }}

      - name: Enable ccache
        run: |
          apt-get update
          apt-get install -y ccache
          echo "/usr/lib/ccache" >> $GITHUB_PATH
          mkdir -p ~/.ccache
          echo "max_size = 5.0G" > ~/.ccache/ccache.conf

      # ================
      # Install Ignition
      # ================

      - name: '[Stable Channel] Install Ignition ${{ matrix.ignition }}'
        if: |
          github.ref == 'refs/heads/master' ||
          (github.event_name == 'pull_request' && github.event.pull_request.head.ref == 'refs/heads/master')
        run: |
          sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" >\
            /etc/apt/sources.list.d/gazebo-stable.list'
          wget http://packages.osrfoundation.org/gazebo.key -O - | apt-key add -
          apt-get update
          apt-get install -y --no-install-recommends ignition-${{ matrix.ignition }}

      - name: '[Nightly Channel] Install Ignition ${{ matrix.ignition }}'
        if: |
          (github.event_name == 'push' && github.ref != 'refs/heads/master') ||
          (github.event_name == 'pull_request' && github.event.pull_request.head.ref != 'refs/heads/master')
        run: |
          sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" >\
            /etc/apt/sources.list.d/gazebo-stable.list'
          wget http://packages.osrfoundation.org/gazebo.key -O - | apt-key add -
          apt-get update
          pip3 install vcstool colcon-common-extensions
          mkdir -p /workspace/src
          cd /workspace/src
          wget -O - ${TAGS_YAML} | vcs import
          SYSTEM_VERSION=$(lsb_release -cs)
          apt-get -y install $(sort -u $(find . -iname 'packages-'$SYSTEM_VERSION'.apt' -o -iname 'packages.apt') | tr '\n' ' ')
          cd /workspace
          colcon graph
          colcon build \
              --cmake-args \
                  -GNinja \
                  -DBUILD_TESTING:BOOL=OFF \
                  -DCMAKE_BUILD_TYPE=Debug \
              --merge-install
          echo "source /workspace/install/setup.bash" >> /etc/bash.bashrc
        env:
          TAGS_YAML: https://raw.githubusercontent.com/ignition-tooling/gazebodistro/master/collection-${{ matrix.ignition }}.yaml

      # ==========================
      # Install other dependencies
      # ==========================

      - name: Install iDynTree
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
            python3-numpy libxml2-dev coinor-libipopt-dev libeigen3-dev libassimp-dev swig
          pip3 install git+https://github.com/robotology/idyntree@devel
          IDYNTREE_PYTHON_PKG=$(python3 -c 'import idyntree, pathlib; print(pathlib.Path(idyntree.__file__).parent)')
          echo "CMAKE_PREFIX_PATH=$IDYNTREE_PYTHON_PKG" >> $GITHUB_ENV

      # =============
      # Build project
      # =============

      # Note: In order to execute the setup.sh script, the file /etc/bash.bashrc must be sourced.
      #       To do that, we change the shell to a bash interactive session.

      # Developer installation
      - name: '[Developer] Build and Install C++'
        if: matrix.type == 'Developer'
        shell: bash -i -e {0}
        run: |
          env
          mkdir build && cd build
          cmake .. \
            -GNinja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DIGNITION_DISTRIBUTION=$(python3 -c "print('${{ matrix.ignition }}'.capitalize())")
          cmake --build . --target install
      - name: '[Developer] Setup Python Package'
        if: matrix.type == 'Developer'
        run: pip3 install -e .

      # User installation
      - name: '[User] Create wheel'
        if: matrix.type == 'User'
        shell: bash -i -e {0}
        run: |
          python3 setup.py \
            bdist_wheel \
            build_ext -DIGNITION_DISTRIBUTION=$(python3 -c "print('${{ matrix.ignition }}'.capitalize())")
      - name: '[User] Install local wheel'
        if: matrix.type == 'User'
        run: |
          cd dist
          pip3 install -v *.whl

      # ============
      # Test project
      # ============

      - name: '[ScenarI/O] Python Tests'
        run: |
          cd tests
          pytest -m "scenario"

      - name: '[ScenarI/O] Python Tests with Valgrind'
        if: failure()
        run: |
          apt-get install -y --no-install-recommends valgrind
          pip3 install colour-valgrind
          cd tests
          valgrind --log-file=/tmp/valgrind.log pytest -s -m "scenario" || colour-valgrind -t /tmp/valgrind.log

      - name: '[gym_ignition] Python Tests'
        run: |
          cd tests
          pytest -m "gym_ignition"

      - name: '[gym_ignition] Python Tests with Valgrind'
        if: failure()
        run: |
          pip3 install colour-valgrind
          cd tests
          valgrind --log-file=/tmp/valgrind.log pytest -s -m "gym_ignition" || colour-valgrind -t /tmp/valgrind.log
